{% set name = "gravelamps" %}
{% set version = "2.3.1rc14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/mick.wright/Gravelamps/-/archive/{{ version }}/Gravelamps-{{ version }}.tar.gz
  sha256: a46aba53cf8018be4deb0274c7caa14215c28c4cb73409ec86c5b12b568f7508

build:
  entry_points:
    - gravelamps_inference=gravelamps.inference:main
    - gravelamps_generate_lens=gravelamps.generate_lens:main
    - gravelamps_generate_interpolator_data=gravelamps.lensing.generic:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not linux or py<=39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - libgomp  # [linux]
  host:
    - python
    - setuptools-scm
    - pip
    - arb
    - libflint
    - boost-cpp
  run:
    - python
    - asimov
    - astropy
    - bilby
    - bilby_pipe
    - python-htcondor
    - numpy
    - scipy

test:
  imports:
    - gravelamps
    - gravelamps.lensing.point
  commands:
    - pip check
    - gravelamps_inference --help
    - gravelamps_generate_lens --help
    - gravelamps_generate_interpolator_data --help
  requires:
    - pip

about:
  home: https://git.ligo.org/mick.wright/Gravelamps
  summary: Software package designed for running template based analysis of lensed gravitational wave signals to determine the lens profile model. Built on top of the parameter estimation framework, Bilby, and arbitrary precision library arb
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mick-wright
