{% set name = "gravelamps" %}
{% set version = "2.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/mick.wright/Gravelamps/-/archive/{{ version }}/Gravelamps-{{ version }}.tar.gz
  sha256: 89db867b73f63487823209310efe4c2d56388233f9da807b23fe84548999c855
build:
  entry_points:
    - gravelamps_inference=gravelamps.inference:main
    - gravelamps_generate_lens=gravelamps.generate_lens:main
    - gravelamps_generate_interpolator_data=gravelamps.lensing.generic:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [win or py<=39 or py >= 312]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libflint
    - libboost-headers
    - {{ compiler('cxx') }}  # [osx]
  run:
    - python
    - asimov
    - astropy-base <7.0
    - bilby
    - bilby_pipe
    - python-htcondor
    - numpy
    - scipy <1.14.0

test:
  imports:
    - gravelamps
    - gravelamps.lensing.point
  commands:
    - pip check
    - gravelamps_inference --help
    - gravelamps_generate_lens --help
    - gravelamps_generate_interpolator_data --help
  requires:
    - pip

about:
  home: https://git.ligo.org/mick.wright/Gravelamps
  summary: Software package designed for running template based analysis of lensed gravitational wave signals to determine the lens profile model. Built on top of the parameter estimation framework, Bilby, and arbitrary precision library arb
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mick-wright
